Repository Bearsampp/sandbox, pull requests merged in 2024-05, with the labels that each got.

#6 syncing readme
  .github/workflows/sync.yml
  README.md
Labels: documentation, enhancement, Review effort [1-5]: 2

#4 Pr-agent fix
  core/classes/tpls/class.tpl.aestan.php
Labels: bug, Review effort [1-5]: 2, Bug fix

#2 Update status badge colors in ajax.nodejs.php and ajax.php.php for cl…
  core/resources/homepage/ajax/ajax.nodejs.php
  core/resources/homepage/ajax/ajax.php.php
Labels: enhancement, Review effort [1-5]: 2

#12 imagse path optimization
  core/resources/homepage/homepage.php
  core/resources/homepage/tpls/hp.apache.html
  core/resources/homepage/tpls/hp.filezilla.html
  core/resources/homepage/tpls/hp.mailhog.html
  core/resources/homepage/tpls/hp.mariadb.html
  core/resources/homepage/tpls/hp.memcached.html
  core/resources/homepage/tpls/hp.mysql.html
  core/resources/homepage/tpls/hp.nodejs.html
  core/resources/homepage/tpls/hp.php.html
  core/resources/homepage/tpls/hp.postgresql.html
Labels: documentation, enhancement, Review effort [1-5]: 2

#11 redoes display of "download more' in right menu
  core/classes/tpls/app/class.tpl.app.apache.php
  core/classes/tpls/app/class.tpl.app.filezilla.php
  core/classes/tpls/app/class.tpl.app.mailhog.php
  core/classes/tpls/app/class.tpl.app.mariadb.php
  core/classes/tpls/app/class.tpl.app.memcached.php
  core/classes/tpls/app/class.tpl.app.mysql.php
  core/classes/tpls/app/class.tpl.app.nodejs.php
  core/classes/tpls/app/class.tpl.app.php.php
  core/classes/tpls/app/class.tpl.app.postgresql.php
Labels: documentation, enhancement, Review effort [1-5]: 2

#9 simple docblock
  core/classes/class.config.php
  core/resources/homepage/ajax/ajax.apache.php
  core/resources/homepage/ajax/ajax.filezilla.php
  core/resources/homepage/ajax/ajax.mariadb.php
  core/resources/homepage/ajax/ajax.memcached.php
  core/resources/homepage/ajax/ajax.mysql.php
  core/resources/homepage/ajax/ajax.nodejs.php
  core/resources/homepage/ajax/ajax.php.php
  core/resources/homepage/ajax/ajax.postgresql.php
  core/resources/homepage/ajax/ajax.summary.php
  core/resources/homepage/js/filezilla.js
  core/resources/homepage/js/latestversion.js
  core/resources/homepage/js/mailhog.js
  core/resources/homepage/js/mariadb.js
  core/resources/homepage/js/memcached.js
  core/resources/homepage/js/mysql.js
  core/resources/homepage/js/nodejs.js
  core/resources/homepage/js/php.js
  core/resources/homepage/js/postgresql.js
  core/resources/homepage/js/summary.js
Labels: documentation, enhancement, Review effort [1-5]: 2

#16 syntax fix
  core/classes/tpls/app/class.tpl.app.filezilla.php
  core/classes/tpls/app/class.tpl.app.nodejs.php
Labels: enhancement, Bug fix

#17 Removing JQuery from Home Page, adding close on click and formatting for latest version, adding try/catch to stop json failures
  core/classes/tpls/app/class.tpl.app.nodejs.php
  core/classes/tpls/class.tpl.aestan.php
  core/resources/homepage/ajax/ajax.latestversion.php
  core/resources/homepage/ajax/ajax.summary.php
  core/resources/homepage/css/app.css
  core/resources/homepage/homepage.php
  core/resources/homepage/js/_commons.js
  core/resources/homepage/js/latestversion.js
  core/resources/homepage/js/mysql.js
  core/resources/homepage/tpls/hp.latestversion.html
Labels: enhancement, Bug fix, Review effort [1-5]: 3

#18 Fixes #3
  core/classes/actions/class.action.checkVersion.php
  core/resources/homepage/tpls/hp.latestversion.html
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#19 spanish translation
  core/langs/spanish.lang
Labels: documentation, enhancement, Review effort [1-5]: 2

#20 elliipsis removal
  core/classes/class.lang.php
  core/classes/class.splash.php
  core/classes/tpls/class.tpl.consolez.php
  core/langs/english.lang
  core/langs/french.lang
  core/langs/hungarian.lang
  core/langs/swedish.lang
Labels: documentation, enhancement

#21 wider modal box
  core/classes/actions/class.action.about.php
Labels: enhancement, Review effort [1-5]: 2

#23 sync was missing
  .github/sync.yml
  .github/workflows/sync.yml
Labels: enhancement, Review effort [1-5]: 2, configuration changes

#24 sync errors
  .github/sync.yml
  core/resources/homepage/img/icons/bearsampp.bmp
Labels: Review effort [1-5]: 1, configuration changes

#26 Update class.tpl.aestan.php to revert previous change
  core/classes/tpls/class.tpl.aestan.php
Labels: Review effort [1-5]: 1, Bug fix

#27 Fixes Bearsampp #372
  .gitignore
  core/classes/tpls/class.tpl.aestan.php
  core/resources/version.dat
Labels: documentation, enhancement, Review effort [1-5]: 2
