Repository Bearsampp/sandbox, pull requests merged in 2024-05, with the labels that each got.

#5 Change language functionality - DO THIS BEFORE #3
  core/classes/actions/class.action.checkVersion.php
  core/classes/class.config.php
  core/classes/class.core.php
  core/classes/class.langproc.php
  core/classes/class.util.php
  core/langs/english.lang
  core/langs/french.lang
  core/langs/hungarian.lang
  core/langs/russian.lang
  core/langs/swedish.lang
  core/libs/php/ext/php_zip.dll
  core/libs/php/php.ini
  core/resources/github.zip
  core/resources/homepage/ajax/ajax.latestversion.php
  core/resources/homepage/css/app.css
  core/resources/homepage/homepage.php
  core/root.php
Labels: enhancement, bug_fix, Review effort [1-5]: 4

#11 minor fixes
  core/classes/class.util.php
  core/resources/homepage/ajax/ajax.latestversion.php
Labels: enhancement, bug_fix, Review effort [1-5]: 2

#10 Turn off favicon in splash screen
  core/classes/class.winbinder.php
Labels: bug_fix, Review effort [1-5]: 2

#12 PAT Setup
  core/classes/class.core.php
  core/classes/class.util.php
  core/resources/github.zip
  core/resources/homepage/ajax/ajax.latestversion.php
  core/resources/homepage/homepage.php
  core/root.php
Labels: enhancement

#13 Language Refactor
  .gitignore
  core/classes/class.langproc.php
  core/langs/english.lang
  core/langs/french.lang
  core/langs/hungarian.lang
  core/langs/russian.lang
  core/langs/swedish.lang
  core/libs/openssl/openssl.cfg
Labels: enhancement, Review effort [1-5]: 2

#14 homepage fixes
  core/resources/homepage/ajax/ajax.apache.php
  core/resources/homepage/ajax/ajax.latestversion.php
  core/resources/homepage/ajax/ajax.php.php
  core/resources/homepage/ajax/ajax.summary.php
  core/resources/homepage/css/app.css
  core/resources/homepage/homepage.php
  core/resources/homepage/img/discord.png
  core/resources/homepage/img/donate.png
  core/resources/homepage/tpls/hp.index.apache.php
  core/resources/homepage/tpls/hp.index.filezilla.php
  core/resources/homepage/tpls/hp.index.mailhog.php
  core/resources/homepage/tpls/hp.index.mariadb.php
  core/resources/homepage/tpls/hp.index.memcached.php
  core/resources/homepage/tpls/hp.index.mysql.php
  core/resources/homepage/tpls/hp.index.nodejs.php
  core/resources/homepage/tpls/hp.index.php.php
  core/resources/homepage/tpls/hp.index.postgresql.php
  core/resources/homepage/tpls/hp.index.summary.php
  core/resources/homepage/tpls/hp.latestversion.php
  core/resources/homepage/tpls/hp.phpinfo.php
Labels: enhancement, bug_fix, Review effort [1-5]: 2

#15 fixes #361
  core/resources/homepage/ajax/ajax.latestversion.php
Labels: bug, bug_fix, Review effort [1-5]: 1

#18 remove ... and fix width of about
  core/classes/actions/class.action.about.php
  core/classes/actions/class.action.checkVersion.php
  core/classes/actions/class.action.startup.php
  core/classes/apps/class.app.adminer.php
  core/classes/apps/class.app.phpmyadmin.php
  core/classes/apps/class.app.phppgadmin.php
  core/classes/apps/class.app.webgrind.php
  core/classes/bins/class.bin.apache.php
  core/classes/bins/class.bin.filezilla.php
  core/classes/bins/class.bin.mailhog.php
  core/classes/bins/class.bin.mariadb.php
  core/classes/bins/class.bin.memcached.php
  core/classes/bins/class.bin.mysql.php
  core/classes/bins/class.bin.nodejs.php
  core/classes/bins/class.bin.php.php
  core/classes/bins/class.bin.postgresql.php
  core/classes/class.autoloader.php
  core/classes/class.lang.php
  core/classes/class.module.php
  core/classes/class.splash.php
  core/classes/tools/class.tool.git.php
  core/classes/tpls/class.tpl.consolez.php
  core/langs/english.lang
  core/langs/french.lang
  core/libs/winbinder/db/db_common.inc.php
  core/root.php
Labels: documentation, enhancement, Review effort [1-5]: 3

#19 homepage fixes
  core/resources/homepage/ajax/ajax.apache.php
  core/resources/homepage/ajax/ajax.latestversion.php
  core/resources/homepage/ajax/ajax.php.php
  core/resources/homepage/css/app.css
  core/resources/homepage/homepage.php
  core/resources/homepage/tpls/hp.index.apache.php
  core/resources/homepage/tpls/hp.index.filezilla.php
  core/resources/homepage/tpls/hp.index.mailhog.php
  core/resources/homepage/tpls/hp.index.mariadb.php
  core/resources/homepage/tpls/hp.index.memcached.php
  core/resources/homepage/tpls/hp.index.mysql.php
  core/resources/homepage/tpls/hp.index.nodejs.php
  core/resources/homepage/tpls/hp.index.php.php
  core/resources/homepage/tpls/hp.index.postgresql.php
  core/resources/homepage/tpls/hp.index.summary.php
  core/resources/homepage/tpls/hp.latestversion.php
  core/resources/homepage/tpls/hp.phpinfo.php
  core/resources/version.dat
Labels: enhancement, bug_fix, Review effort [1-5]: 3

#24 VBS error on startup fix
  core/classes/actions/class.action.quit.php
  core/classes/class.symlinks.php
  core/classes/class.util.php
  core/root.php
Labels: enhancement, bug_fix, Review effort [1-5]: 3

#26 fix splash screen progress bar
  core/classes/actions/class.action.about.php
  core/classes/class.splash.php
Labels: Review effort [1-5]: 1, Bug fix

#27 Elipsis removal
  core/classes/actions/class.action.startup.php
  core/classes/apps/class.app.adminer.php
  core/classes/apps/class.app.phpmyadmin.php
  core/classes/apps/class.app.phppgadmin.php
  core/classes/apps/class.app.webgrind.php
  core/classes/bins/class.bin.apache.php
  core/classes/bins/class.bin.filezilla.php
  core/classes/bins/class.bin.mailhog.php
  core/classes/bins/class.bin.mariadb.php
  core/classes/bins/class.bin.memcached.php
  core/classes/bins/class.bin.mysql.php
  core/classes/bins/class.bin.nodejs.php
  core/classes/bins/class.bin.php.php
  core/classes/bins/class.bin.postgresql.php
  core/classes/class.module.php
  core/classes/class.splash.php
  core/classes/tools/class.tool.git.php
Labels: enhancement, Review effort [1-5]: 2

#28 Language standardization
  core/classes/class.langproc.php
  core/langs/english.lang
  core/langs/french.lang
  core/langs/hungarian.lang
  core/langs/russian.lng
  core/langs/swedish.lang
Labels: enhancement, Review effort [1-5]: 2

#25 log file skip fix
  core/classes/class.util.php
Labels: enhancement, bug_fix, Review effort [1-5]: 2

#21 All jQuery commented out and rewritten as pure Javascript.
  core/classes/class.homepage.php
  core/resources/homepage/js/_commons.js
  core/resources/homepage/js/apache.js
  core/resources/homepage/js/filezilla.js
  core/resources/homepage/js/latestversion.js
  core/resources/homepage/js/mailhog.js
  core/resources/homepage/js/mariadb.js
  core/resources/homepage/js/memcached.js
  core/resources/homepage/js/mysql.js
  core/resources/homepage/js/nodejs.js
  core/resources/homepage/js/php.js
  core/resources/homepage/js/postgresql.js
  core/resources/homepage/js/summary.js
Labels: enhancement, Review effort [1-5]: 3
