Repository Bearsampp/sandbox, pull requests merged in 2025-04, with the labels that each got.

#138 🔧 Optimize PHP configuration by removing deprecated directives and increasing memory limit to 256MB
  core/libs/php/php.ini
Labels: enhancement :sparkles:, Review effort 2/5

#139 fixes
  core/classes/actions/class.action.loading.php
  core/classes/class.core.php
  core/classes/class.splash.php
  core/classes/class.winbinder.php
  core/resources/homepage/ajax.php
Labels: enhancement :sparkles:, Review effort 2/5

#140 warnings
  core/classes/class.winbinder.php
Labels: bug :bug:, Review effort 2/5

#143 FIXES AN ISSUE WHERE "Check for update" BROKE.
  core/classes/actions/class.action.checkVersion.php
  core/classes/actions/class.action.exec.php
  core/classes/class.win32ps.php
Labels: bug :bug:

#144 🖼️ Update image paths to use dedicated methods instead of resources path
  .gitignore
  core/classes/actions/class.action.about.php
  core/classes/actions/class.action.checkVersion.php
  core/classes/class.vbs.php
Labels: bug :bug:, Review effort 2/5

#147 IncludePR
  .gitignore
  README.md
  core/classes/actions/class.action.quickPick.php
  core/classes/class.config.php
  core/classes/class.util.php
  core/resources/github.dat
  core/resources/homepage/css/app.css
  core/resources/homepage/homepage.php
  core/resources/homepage/js/loading-cursor.js
  core/resources/homepage/js/quickpick.js
Labels: enhancement :sparkles:, Review effort 2/5

#148 ⏱️ Improve timeout handling and service checks for more reliable startup and shutdown
  core/classes/actions/class.action.loading.php
  core/classes/actions/class.action.quit.php
  core/classes/actions/class.action.startup.php
Labels: enhancement :sparkles:

#149 quickpick
  .gitignore
  core/classes/actions/class.action.quickPick.php
  core/classes/class.config.php
  core/resources/homepage/ajax/ajax.quickpick.php
Labels: bug :bug:, Review effort 4/5
