Repository Bearsampp/sandbox, pull requests merged in 2025-02, with the labels that each got.

#95 corrects issue where date of last quickpick.json was not checked properly. adds autologger for header when logsverbose is set to 2 ( 'debug')
  .gitignore
  core/classes/actions/class.action.quickPick.php
Labels: bug, Review effort [1-5]: 2

#98 update to 7zip 24.09 in core
  core/libs/7zip/7za.dll
  core/libs/7zip/7za.exe
  core/libs/7zip/7zxa.dll
Labels: enhancement

#99 Add required empty owner and event_type fields in workflow dispatch
  .github/workflows/dispatcher.yml
Labels: Review effort 1/5

#101 test
  .github/workflows/dispatcher.yml
Labels: Review effort 1/5

#102 test
  .github/workflows/dispatcher.yml
Labels: Review effort 1/5

#103 test
  .github/workflows/dispatcher.yml
Labels: Review effort 1/5

#104 test
  .github/workflows/dispatcher.yml
Labels: Review effort 1/5

#106 test
  .github/workflows/dispatcher.yml
Labels: Review effort 1/5

#109 deprecation
  .github/workflows/dispatcher.yml
  .gitignore
  core/resources/homepage/libs/fontawesome/svgs/brands/css.svg
  core/resources/homepage/libs/fontawesome/svgs/brands/files-pinwheel.svg
  core/resources/homepage/libs/fontawesome/svgs/brands/square-bluesky.svg
  core/resources/homepage/libs/fontawesome/svgs/solid/chart-diagram.svg
  core/resources/homepage/libs/fontawesome/svgs/solid/comment-nodes.svg
  core/resources/homepage/libs/fontawesome/svgs/solid/file-fragment.svg
  core/resources/homepage/libs/fontawesome/svgs/solid/file-half-dashed.svg
  core/resources/homepage/libs/fontawesome/svgs/solid/hexagon-nodes-bolt.svg
  core/resources/homepage/libs/fontawesome/svgs/solid/hexagon-nodes.svg
  core/resources/homepage/libs/fontawesome/svgs/solid/square-binary.svg
  fix-icon.bat
Labels: Bug fix, Review effort 2/5

#110 Refactor PostgreSQL port check with improved connection handling
  core/classes/bins/class.bin.postgresql.php
Labels: bug, Review effort 3/5

#112 apache
  core/resources/homepage/ajax/ajax.apache.php
  core/resources/homepage/homepage.php
  core/resources/homepage/js/apache.js
  core/resources/homepage/tpls/hp.apache.html
  core/resources/homepage/tpls/hp.php.html
  core/resources/homepage/tpls/hp.postgresql.html
Labels: bug, Bug fix, Review effort 2/5

#113 apache
  .github/workflows/sync.yml
Labels: bug, Review effort 1/5
